# Generated by Django 3.0.1 on 2020-02-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('hashtag', models.CharField(help_text='По hashtag осуществляется поиск описаний в Вики', max_length=60, verbose_name='Hashtag')),
                ('biscuit_icon', models.CharField(default='/static/icons/constructor/BiscuitCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('honey_icon', models.CharField(default='/static/icons/constructor/HoneyCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('cup_icon', models.CharField(default='/static/icons/constructor/CupCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('pop_up_icon', models.CharField(default='/static/icons/popup/.svg', max_length=120, verbose_name='Иконка в всплывающем меню')),
            ],
            options={
                'verbose_name': 'Бисквит',
                'verbose_name_plural': 'Бисквиты',
            },
        ),
        migrations.CreateModel(
            name='Cream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('hashtag', models.CharField(help_text='По hashtag осуществляется поиск описаний в Вики', max_length=60, verbose_name='Hashtag')),
                ('biscuit_icon', models.CharField(default='/static/icons/constructor/BiscuitCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('honey_icon', models.CharField(default='/static/icons/constructor/HoneyCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('cup_icon', models.CharField(default='/static/icons/constructor/CupCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('pop_up_icon', models.CharField(default='/static/icons/popup/.svg', max_length=120, verbose_name='Иконка в всплывающем меню')),
            ],
            options={
                'verbose_name': 'Крем',
                'verbose_name_plural': 'Кремы',
            },
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('hashtag', models.CharField(help_text='По hashtag осуществляется поиск описаний в Вики', max_length=60, verbose_name='Hashtag')),
                ('biscuit_icon', models.CharField(default='/static/icons/constructor/BiscuitCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('honey_icon', models.CharField(default='/static/icons/constructor/HoneyCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('cup_icon', models.CharField(default='/static/icons/constructor/CupCake/.svg', max_length=120, verbose_name='Иконка в конструкторе')),
                ('pop_up_icon', models.CharField(default='/static/icons/popup/.svg', max_length=120, verbose_name='Иконка в всплывающем меню')),
            ],
            options={
                'verbose_name': 'Начинка',
                'verbose_name_plural': 'Начинки',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
            ],
        ),
    ]
