# Generated by Django 3.0.1 on 2020-02-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='avalibleBiscuits',
            field=models.ManyToManyField(blank=True, related_name='avalibleFillings', to='constructor.Biscuit', verbose_name='Доступные бисквиты'),
        ),
        migrations.AddField(
            model_name='filling',
            name='avalibleCreams',
            field=models.ManyToManyField(blank=True, related_name='avalibleFillings', to='constructor.Cream', verbose_name='Доступные кремы'),
        ),
    ]
