# Generated by Django 3.0.1 on 2020-02-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_auto_20200215_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filling',
            old_name='avalibleBiscuits',
            new_name='avalible_biscuits',
        ),
        migrations.RenameField(
            model_name='filling',
            old_name='avalibleCreams',
            new_name='avalible_creams',
        ),
    ]
