# Generated by Django 3.0.1 on 2020-02-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0011_auto_20200224_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='fillColor',
            field=models.CharField(default='hsl( , %, %)', max_length=50, verbose_name='Цвет заливки'),
        ),
        migrations.AddField(
            model_name='biscuit',
            name='strokeColor',
            field=models.CharField(default='hsl( , %, %)', max_length=60, verbose_name='Цвет обводки'),
        ),
        migrations.AddField(
            model_name='cream',
            name='fillColor',
            field=models.CharField(default='hsl( , %, %)', max_length=50, verbose_name='Цвет заливки'),
        ),
        migrations.AddField(
            model_name='cream',
            name='strokeColor',
            field=models.CharField(default='hsl( , %, %)', max_length=60, verbose_name='Цвет обводки'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillColor',
            field=models.CharField(default='hsl( , %, %)', max_length=50, verbose_name='Цвет заливки'),
        ),
        migrations.AddField(
            model_name='filling',
            name='strokeColor',
            field=models.CharField(default='hsl( , %, %)', max_length=60, verbose_name='Цвет обводки'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='hashtag',
            field=models.CharField(help_text='По hashtag осуществляется поиск описаний в Вики', max_length=50, verbose_name='Hashtag'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='hashtag',
            field=models.CharField(help_text='По hashtag осуществляется поиск описаний в Вики', max_length=50, verbose_name='Hashtag'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='hashtag',
            field=models.CharField(help_text='По hashtag осуществляется поиск описаний в Вики', max_length=50, verbose_name='Hashtag'),
        ),
    ]
