# Generated by Django 3.0.1 on 2020-03-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='busy_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=90, verbose_name='Заказчик')),
                ('contact', models.CharField(max_length=90, verbose_name='Контакт')),
                ('date', models.DateField(verbose_name='Дата')),
                ('prod_type', models.CharField(blank=True, max_length=90, verbose_name='Тип продукции')),
                ('parts', models.CharField(max_length=300, verbose_name='Итгредиенты')),
                ('details', models.CharField(max_length=90, verbose_name='Детали')),
                ('comment', models.TextField(verbose_name='Комметарий')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date'],
            },
        ),
    ]
