# Generated by Django 3.0.1 on 2020-03-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='busy_date',
            new_name='Order',
        ),
    ]
