# Generated by Django 3.0.1 on 2020-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0002_auto_20200312_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комметарий'),
        ),
    ]
