# Generated by Django 3.0.1 on 2020-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_auto_20200215_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='avalible_biscuits_in_cup',
            field=models.ManyToManyField(blank=True, related_name='avalibleCupFillings', to='constructor.Biscuit', verbose_name='Доступные бисквиты в капкейке'),
        ),
        migrations.AddField(
            model_name='filling',
            name='avalible_biscuits_in_honey',
            field=models.ManyToManyField(blank=True, related_name='avalibleHoneyFillings', to='constructor.Biscuit', verbose_name='Доступные бисквиты в открытом медовике'),
        ),
        migrations.AddField(
            model_name='filling',
            name='avalible_creams_in_cup',
            field=models.ManyToManyField(blank=True, related_name='avalibleCupFillings', to='constructor.Cream', verbose_name='Доступные кремы в капкейке'),
        ),
        migrations.AddField(
            model_name='filling',
            name='avalible_creams_in_honey',
            field=models.ManyToManyField(blank=True, related_name='avalibleHoneyFillings', to='constructor.Cream', verbose_name='Доступные кремы в открытом медовике'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='biscuit_icon',
            field=models.CharField(default='/static/icons/constructor/BiscuitCake/.svg', help_text='Иконка в конструкторе бисквитного торта', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='cup_icon',
            field=models.CharField(default='/static/icons/constructor/CupCake/.svg', help_text='Иконка в конструкторе капкейка', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='honey_icon',
            field=models.CharField(default='/static/icons/constructor/HoneyCake/.svg', help_text='Иконка в конструкторе откытого медовика', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='name',
            field=models.CharField(help_text='ИСпользуется везде где упоминается элемент', max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='pop_up_icon',
            field=models.CharField(default='/static/icons/popup/.svg', help_text='Иконка в Pop Up, одинаковая для всех конструкторов', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='biscuit_icon',
            field=models.CharField(default='/static/icons/constructor/BiscuitCake/.svg', help_text='Иконка в конструкторе бисквитного торта', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='cup_icon',
            field=models.CharField(default='/static/icons/constructor/CupCake/.svg', help_text='Иконка в конструкторе капкейка', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='honey_icon',
            field=models.CharField(default='/static/icons/constructor/HoneyCake/.svg', help_text='Иконка в конструкторе откытого медовика', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='name',
            field=models.CharField(help_text='ИСпользуется везде где упоминается элемент', max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='pop_up_icon',
            field=models.CharField(default='/static/icons/popup/.svg', help_text='Иконка в Pop Up, одинаковая для всех конструкторов', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='avalible_biscuits_in_biscuit',
            field=models.ManyToManyField(blank=True, related_name='avalibleBiscuitFillings', to='constructor.Biscuit', verbose_name='Доступные бисквиты в бисквитном торте'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='avalible_creams_in_biscuit',
            field=models.ManyToManyField(blank=True, related_name='avalibleBiscuitFillings', to='constructor.Cream', verbose_name='Доступные кремы в бисквитном торте'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='biscuit_icon',
            field=models.CharField(default='/static/icons/constructor/BiscuitCake/.svg', help_text='Иконка в конструкторе бисквитного торта', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='cup_icon',
            field=models.CharField(default='/static/icons/constructor/CupCake/.svg', help_text='Иконка в конструкторе капкейка', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='honey_icon',
            field=models.CharField(default='/static/icons/constructor/HoneyCake/.svg', help_text='Иконка в конструкторе откытого медовика', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='name',
            field=models.CharField(help_text='ИСпользуется везде где упоминается элемент', max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='pop_up_icon',
            field=models.CharField(default='/static/icons/popup/.svg', help_text='Иконка в Pop Up, одинаковая для всех конструкторов', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
    ]
