# Generated by Django 3.0.1 on 2020-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_auto_20200215_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='used_in_biscuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biscuit',
            name='used_in_cup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biscuit',
            name='used_in_honey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cream',
            name='used_in_biscuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cream',
            name='used_in_cup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cream',
            name='used_in_honey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filling',
            name='used_in_biscuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filling',
            name='used_in_cup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filling',
            name='used_in_honey',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='name',
            field=models.CharField(help_text='Используется везде где упоминается элемент', max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='name',
            field=models.CharField(help_text='Используется везде где упоминается элемент', max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='name',
            field=models.CharField(help_text='Используется везде где упоминается элемент', max_length=60, verbose_name='Название'),
        ),
    ]
