# Generated by Django 3.0.1 on 2020-02-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_auto_20200215_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuit',
            name='biscuit_icon',
            field=models.CharField(default='/static/icons/constructor/BiscuitCake/', help_text='Иконка в конструкторе бисквитного торта', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='cup_icon',
            field=models.CharField(default='/static/icons/constructor/CupCake/', help_text='Иконка в конструкторе капкейка', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='honey_icon',
            field=models.CharField(default='/static/icons/constructor/HoneyCake/', help_text='Иконка в конструкторе откытого медовика', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='pop_up_icon',
            field=models.CharField(default='/static/icons/popup/', help_text='Иконка в Pop Up, одинаковая для всех конструкторов', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='biscuit_icon',
            field=models.CharField(default='/static/icons/constructor/BiscuitCake/', help_text='Иконка в конструкторе бисквитного торта', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='cup_icon',
            field=models.CharField(default='/static/icons/constructor/CupCake/', help_text='Иконка в конструкторе капкейка', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='honey_cream_second_icon',
            field=models.CharField(default='/static/icons/constructor/HoneyCake/', help_text='Иконка в конструкторе медовика с нижними слоями', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='honey_icon',
            field=models.CharField(default='/static/icons/constructor/HoneyCake/', help_text='Иконка в конструкторе откытого медовика', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='pop_up_icon',
            field=models.CharField(default='/static/icons/popup/', help_text='Иконка в Pop Up, одинаковая для всех конструкторов', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='biscuit_icon',
            field=models.CharField(default='/static/icons/constructor/BiscuitCake/', help_text='Иконка в конструкторе бисквитного торта', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='cup_icon',
            field=models.CharField(default='/static/icons/constructor/CupCake/', help_text='Иконка в конструкторе капкейка', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='honey_icon',
            field=models.CharField(default='/static/icons/constructor/HoneyCake/', help_text='Иконка в конструкторе откытого медовика', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='pop_up_icon',
            field=models.CharField(default='/static/icons/popup/', help_text='Иконка в Pop Up, одинаковая для всех конструкторов', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
    ]
