# Generated by Django 3.0.1 on 2020-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Используется везде где упоминается элемент', max_length=60, verbose_name='Название')),
                ('color', models.CharField(default='hsl( , %, %)', help_text='Строго в HSL', max_length=20, verbose_name='Цвет')),
                ('used_in_biscuit', models.BooleanField(default=False, verbose_name='Используется в конструкторе бисквитного торта')),
                ('used_in_honey', models.BooleanField(default=False, verbose_name='Используется в конструкторе открытого медовика')),
                ('used_in_cup', models.BooleanField(default=False, verbose_name='Используется в конструкторе капкейка')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(help_text='Напиши здесь описание декора', verbose_name='Описание')),
                ('used_in_biscuit', models.BooleanField(default=False, verbose_name='Используется в конструкторе бисквитного торта')),
                ('used_in_honey', models.BooleanField(default=False, verbose_name='Используется в конструкторе открытого медовика')),
                ('used_in_cup', models.BooleanField(default=False, verbose_name='Используется в конструкторе капкейка')),
            ],
            options={
                'verbose_name': 'Декор',
                'verbose_name_plural': 'Типы декоров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название контсруктора')),
                ('minimal', models.FloatField(help_text='Минимальное  значение', verbose_name='Min')),
                ('maximal', models.FloatField(help_text='Максимальное  значение', verbose_name='Max')),
                ('step', models.FloatField(help_text='Шаг изменения значения', verbose_name='Min')),
                ('dimension', models.CharField(help_text='Шаг изменения значения', max_length=5, verbose_name='Min')),
            ],
            options={
                'verbose_name': 'Вес / Колличество',
                'verbose_name_plural': 'Вес / Колличество',
                'ordering': ['name'],
            },
        ),
    ]
