# Generated by Django 3.0.1 on 2020-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Занятая дата',
                'verbose_name_plural': 'Занятые даты',
                'ordering': ['date'],
            },
        ),
    ]
