# Generated by Django 3.0.1 on 2020-03-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Элемент меню первого уровня', 'verbose_name_plural': 'Элементы меню первого уровня'},
        ),
        migrations.AlterModelOptions(
            name='products_sub',
            options={'verbose_name': 'Элемент меню второго уровня', 'verbose_name_plural': 'Элементы меню второго уровня'},
        ),
    ]
