# Generated by Django 3.0 on 2019-12-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=80)),
                ('href', models.CharField(max_length=120)),
                ('slogan', models.TextField(blank=True)),
            ],
        ),
    ]
