# Generated by Django 3.0 on 2019-12-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikicategores'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiSubCategores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=80)),
                ('href', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.WikiCategores')),
            ],
        ),
    ]
