# Generated by Django 3.0 on 2019-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_wikisubcategores'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiobject',
            name='hashtag',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wikiobject',
            name='text',
            field=models.TextField(default='Hashtag должен сооствтсвовать последнему сегменту URL страницы, что бы был возможен поиск по карточкам. Таким образом новая модель организационной деятельности влечет за собой процесс внедрения и модернизации новых предложений. Повседневная практика показывает, что начало повседневной работы по формированию позиции требуют от нас анализа дальнейших направлений развития. Идейные соображения высшего порядка, а также дальнейшее развитие различных форм деятельности влечет за собой процесс внедрения и модернизации соответствующий условий активизации.'),
        ),
    ]
