# Generated by Django 3.0.1 on 2019-12-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20191217_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikisubcategores',
            name='href',
        ),
        migrations.AddField(
            model_name='wikisubcategores',
            name='hashtag',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wikiobject',
            name='text',
            field=models.TextField(default='Hashtag должен сооствтсвовать последнему сегменту URL страницы, что бы был возможен поиск по карточкам. URL карточки из вики раздела должен имет вид "/Wiki/Card/<hashtag>/. Таким образом необходимо проследить за равенством hashtag в таблицах wiki_subcategores и самом элементе Вики."'),
        ),
    ]
