# Generated by Django 3.0.1 on 2019-12-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20191220_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikicategores',
            name='href',
        ),
    ]
