# Generated by Django 3.0.1 on 2020-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='state',
        ),
        migrations.AddField(
            model_name='bug',
            name='contact',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
