# Generated by Django 3.0.1 on 2019-12-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeConstructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biscuits',
            new_name='Biscuit',
        ),
        migrations.RenameModel(
            old_name='Creams',
            new_name='Cream',
        ),
        migrations.RenameModel(
            old_name='Fillings',
            new_name='Filling',
        ),
    ]
