# Generated by Django 3.0.1 on 2019-12-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeConstructor', '0002_auto_20191227_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='avalibleCreams',
            field=models.ManyToManyField(blank=True, related_name='avalibleBiscuits', to='cakeConstructor.Cream'),
        ),
        migrations.AddField(
            model_name='biscuit',
            name='avalibleFillings',
            field=models.ManyToManyField(blank=True, related_name='avalibleBiscuits', to='cakeConstructor.Filling'),
        ),
        migrations.AddField(
            model_name='filling',
            name='avalibleCreams',
            field=models.ManyToManyField(blank=True, related_name='avalibleFillings', to='cakeConstructor.Cream'),
        ),
    ]
