# Generated by Django 3.0.1 on 2019-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeConstructor', '0003_auto_20191227_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biscuit',
            name='avalibleCreams',
        ),
        migrations.RemoveField(
            model_name='biscuit',
            name='avalibleFillings',
        ),
        migrations.AddField(
            model_name='filling',
            name='avalibleBiscuits',
            field=models.ManyToManyField(blank=True, related_name='avalibleBiscuits', to='cakeConstructor.Cream'),
        ),
    ]
