# Generated by Django 3.0.1 on 2019-12-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeConstructor', '0004_auto_20191227_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='avalibleBiscuits',
            field=models.ManyToManyField(blank=True, related_name='avalibleBiscuits', to='cakeConstructor.Biscuit', verbose_name='Доступные бисквиты'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='avalibleCreams',
            field=models.ManyToManyField(blank=True, related_name='avalibleFillings', to='cakeConstructor.Cream', verbose_name='Доступные кремы'),
        ),
    ]
