# Generated by Django 3.0.1 on 2019-12-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeConstructor', '0005_auto_20191227_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='avalibleBiscuits',
            field=models.ManyToManyField(blank=True, related_name='avalibleFillings', to='cakeConstructor.Biscuit', verbose_name='Доступные бисквиты'),
        ),
    ]
