# Generated by Django 3.0.1 on 2020-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeConstructor', '0006_auto_20191227_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='constructorIcon',
            field=models.CharField(default='/static/icons/constructor/biscuit/', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AddField(
            model_name='biscuit',
            name='popUpIcon',
            field=models.CharField(default='/static/icons/popup/biscuit/', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
        migrations.AddField(
            model_name='cream',
            name='constructorIcon',
            field=models.CharField(default='/static/icons/constructor/cream/', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AddField(
            model_name='cream',
            name='popUpIcon',
            field=models.CharField(default='/static/icons/popup/cream/', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
        migrations.AddField(
            model_name='filling',
            name='constructorIcon',
            field=models.CharField(default='/static/icons/constructor/filling/', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AddField(
            model_name='filling',
            name='popUpIcon',
            field=models.CharField(default='/static/icons/popup/filling/', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
    ]
