# Generated by Django 3.0.1 on 2020-01-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeConstructor', '0007_auto_20200119_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuit',
            name='constructorIcon',
            field=models.CharField(default='/static/icons/constructor/biscuit/default.svg', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='biscuit',
            name='popUpIcon',
            field=models.CharField(default='/static/icons/popup/biscuit/default.svg', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='constructorIcon',
            field=models.CharField(default='/static/icons/constructor/cream/default.svg', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='popUpIcon',
            field=models.CharField(default='/static/icons/popup/cream/default.svg', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='constructorIcon',
            field=models.CharField(default='/static/icons/constructor/filling/default.svg', max_length=120, verbose_name='Иконка в конструкторе'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='popUpIcon',
            field=models.CharField(default='/static/icons/popup/filling/default.svg', max_length=120, verbose_name='Иконка в всплывающем меню'),
        ),
    ]
