# Generated by Django 3.0.1 on 2020-01-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeConstructor', '0008_auto_20200119_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='hashtag',
            field=models.CharField(default='#', max_length=60, verbose_name='Hashtag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cream',
            name='hashtag',
            field=models.CharField(default='#', max_length=60, verbose_name='Hashtag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filling',
            name='hashtag',
            field=models.CharField(default='#', max_length=60, verbose_name='Hashtag'),
            preserve_default=False,
        ),
    ]
