# Generated by Django 3.0.7 on 2020-06-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=80)),
                ('slogan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Вики категоря',
                'verbose_name_plural': 'Вики категории',
            },
        ),
        migrations.CreateModel(
            name='WikiObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('hashtag', models.CharField(max_length=50)),
                ('text', models.TextField(default='Hashtag должен сооствтсвовать хэштэгу из Wiki Subcategores и CakeConstructor объектов, что бы все работало правильно')),
                ('image', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Вики статья',
                'verbose_name_plural': 'Вики статьи',
            },
        ),
        migrations.CreateModel(
            name='WikiSubCategores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=80)),
                ('hashtag', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.WikiCategores')),
            ],
            options={
                'verbose_name': 'Вики подкатегория',
                'verbose_name_plural': 'Вики подкатегории',
            },
        ),
    ]
