# Generated by Django 3.0.7 on 2020-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicategores',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Приоритет(чем меньше тем ближе к верху)'),
        ),
        migrations.AddField(
            model_name='wikisubcategores',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Приоритет(чем меньше тем ближе к верху)'),
        ),
    ]
