# Generated by Django 3.0.1 on 2020-03-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('hashtag', models.CharField(help_text='Должен быть такой же как в ссылке на карточку в меню', max_length=60, verbose_name='Hashtag')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('dim', models.CharField(default='р/шт', help_text='Например тнг/пакетик', max_length=10, verbose_name='Размерность')),
                ('image', models.CharField(default='/static/stock/', max_length=60, verbose_name='Картинка')),
                ('description', models.TextField(help_text='Напиши здесь описание', verbose_name='Описание')),
                ('template', models.TextField(help_text='Общий вид: name_of_element:отображаемое_название (parametrs)', verbose_name='Шаблон рендера элементов заказа')),
            ],
            options={
                'verbose_name': 'Карточка продукции',
                'verbose_name_plural': 'Карточки продукции',
                'ordering': ['name'],
            },
        ),
    ]
