# Generated by Django 3.0.7 on 2020-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerMenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('href', models.CharField(max_length=100, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
            },
        ),
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.CharField(max_length=500, verbose_name='Ссылка на изображение')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='Приоритет(чем меньше тем ближе к верху)')),
            ],
            options={
                'verbose_name': 'Запись на главной странице',
                'verbose_name_plural': 'Записи на главной странице',
            },
        ),
    ]
