# Generated by Django 3.0.7 on 2020-06-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_mainpagecontent_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='href_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='href',
            field=models.CharField(max_length=100, verbose_name='Ссылка на страницу без адреса приложения и протокола'),
        ),
    ]
