# Generated by Django 3.0.1 on 2020-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_burgermenuitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Приоритет(чем меньше тем ближе к верху)'),
            preserve_default=False,
        ),
    ]
